models:
  - title: dolphin
    provider: ollama
    model: dolphin3-24b
  - title: lms_llama
    provider: lmstudio
    model: qwen2.5-coder-32b-instruct-mlx
    systemMessage: You are a helpful assistant that uses tools when appropriate.
    default: true
  - title: ollama_llama
    provider: ollama
    model: llama3.1
  - model: my-model
    title: custom-url-openai-compatible
    apiBase: http://whatever:8080/v1
    provider: openai
  - title: dolphin-r1
    provider: ollama
    model: dolphin3-r1
    temperature: 0.7
    top_k: 40
  - model: claude-3-7-sonnet-latest
    provider: anthropic
    apiKey: "****"
    title: claude
    temperature: 0.7
    top_k: 256
    top_p: 0.9
    max_tokens: 2048
  - model: gpt-4o
    title: gpt-4o
    provider: openai
  - model: o3-mini
    title: o3-mini
    systemMessage: You are an expert software developer. You give helpful and concise responses.
    contextLength: 128000
    maxCompletionTokens: 65536
    apiKey: "****"
    provider: openai
    temperature: 0.2
    top_p: 0.8
  - model: llama3.3:70b-instruct-q3_K_M
    title: llama3.3:70b
    client: http://mammoth:11434
    keep_alive_seconds: '240'
    provider: lmstudio
  - model: qwen2.5:72b-instruct-q3_K_S
    title: qwen2.5:72b
    client: http://mammoth:11434
    keep_alive_seconds: '240'
    provider: lmstudio
mcpServers:
  dolphin-demo-database-sqlite:
    command: uvx
    args:
      - mcp-server-sqlite
      - --db-path
      - "~/.dolphin/dolphin.db"
    tool_timeout: 60
